### ISSUE TITLE
Provide a command line interface which takes a json object/file and return the traced path of a particular key

### ISSUE THREAD

**Issue by Agent-Hellboy** [Agent-Hellboy/trace-dkey#5]

**Comment by AniqJaved** [comment]
I would like to work on this issue✅, but would need more context to understand it✌.

**Comment by Agent-Hellboy** [comment]
check a library named [click](https://pypi.org/project/click/).

you should also check this function of one of my lib to find out how i have used click to accomplish a similar usecase 
https://github.com/Agent-Hellboy/find-unused-import/blob/81f555e5ae42a906a2db6e3049ffe23f7c2c2535/src/find_unused_imports.py#L60

you need to provide a field named entry_points to the setup function as well. for example you can check here https://github.com/Agent-Hellboy/find-unused-import/blob/81f555e5ae42a906a2db6e3049ffe23f7c2c2535/setup.py#L21

but first, try to find the approach

**Comment by TechWiz-3** [comment]
Just curious why would you like Click as opposed to argparse or Typer?

**Comment by Agent-Hellboy** [comment]
>Just curious why would you like Click as opposed to argparse or Typer?

:) It was my personal preference, I will suggest going with argparse as the package will become dependency-free. 

but again why do I prefer argparse 

```
import click

@click.command()
@click.option("--count", default=1, help="Number of greetings.")
@click.option("--name", prompt="Your name", help="The person to greet.")
def hello(count, name):
    """Simple program that greets NAME for a total of COUNT times."""
    for _ in range(count):
        click.echo(f"Hello, {name}!")

if __name__ == '__main__':
    hello()
 ```
 to achieve same in argparse 
 ```
 import argparse

def hello(count, name):
    """Simple program that greets NAME for a total of COUNT times."""
    for _ in range(count):
        print(f"Hello, {name}!")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Process some args.')
    parser.add_argument('--count',type=int,
                        help='an integer for the accumulator')
    parser.add_argument('--name', type=str,
                        help='sum the integers (default: find the max)')

    args = parser.parse_args()
    hello(args.count,args.name)
 ```
 
if you want to do the same thing with argparse then you have to parse cmd args separately and then pass it to your hello function but in click, you can decorate the function 
 
click will handle the ANSI escape sequence for you, which is used to colorize text on the terminal

**Comment by TechWiz-3** [comment]
ahh i see, thanks a lot this was very informative
